More stream items for checking
aiida-vasp/parsevasp pull request #53
Opened 2020-12-16 10:14 UTC by zhubonan

Added more stream items for checking.
Note that IBZKPT is a special case as multiple errors can have this, some of them are actually warnings are not fatal. Hence, I set it to `recovery: true`.

As discussed the suggests are removed unless we are sure it is the right one.

2020-12-16 10:28 UTC, espenfl requested changes
Thanks a lot @zhubonan. Looks great. Just had a few comments related to the `suggestion`.

2020-12-16 10:28 UTC, espenfl commented on parsevasp/stream.yml
> +  suggestion: Set LREAL to False.
I suggest that we remove this `suggestion`. See e.g. recent answer from Martin S. here: `This warning appears if your system is close to a structure with higher symmetry. So depending on the tolerance you set for the determination of the symmetry you'll get either the low or the high symmetry structure. Depending on what you want to do this may cause errors: On the one hand, calculating the high symmetry structure may cause degeneracies between states, which you do not want if you really wanted the low symmetry structure. On the other hand, higher symmetry typically means a more numerically stable and faster calculation. To resolve this you can either symmetrize your structure (to guarantee the high symmetry structure) or break the symmetry further (to guarantee the low symmetry structure)`.

2020-12-16 10:28 UTC, espenfl commented on parsevasp/stream.yml
> +  suggestion: Use the code points to vasp_ncl executable
I suggest we write `suggestion: 'Please make sure to use the VASP executable that has been compiled with the non-colinear functionality (ncl flavor, consult build instructions).`

2020-12-16 10:28 UTC, espenfl commented on parsevasp/stream.yml
> +  suggestion: Reduce symmetric precision, e.g. symprec = 1d-6. Or use a symmetrized structure as the input.
Although I would also support this `suggestion` there might be stuff we do not cover, so I suggest we also remove it.

2020-12-28 20:07 UTC, espenfl commented
@zhubonan I took the liberty to force push to a clean rebase from develop and update the suggestions. Thanks a lot for the contribution. I will now merge it.

2020-12-28 20:07 UTC, espenfl approved these changes

2020-12-28 20:19 UTC, zhubonan commented
Cool thanks. Sorry it slipped from my list earlier on!

2020-12-28 20:28 UTC, espenfl commented
@zhubonan No problem. Although, the strategy here does not sit right with me as by force pushing I formally take over the contribution. I have now fixed the tests etc. and if you want, please reset soft and do a new commit and force it yourself. That would be more ideal as this is your contribution. However, if you are okey with this, I will proceed with the merge.

2020-12-28 22:14 UTC, zhubonan commented
@espenfl no worries, just proceed with the merge! Thanks for the final touches!

2020-12-29 15:25 UTC, merged